Repository code4romania/taskforce-fe-components, pull requests merged in 2020-03, with the labels that each got.

#48 feat: add value prop to the listItem component
  src/components/list-item/list-item.js
  src/components/list-item/list-item.stories.js
Labels: enhancement, high priority

#45 exported all components;
  package-lock.json
  package.json
  rollup.config.js
  src/components/footer/footer.js
  src/components/footer/footer.stories.js
  src/index.js
Labels: high priority

#66 [Feature] Implement accordion component
  package-lock.json
  src/components/accordion/accordion.js
  src/components/accordion/accordion.scss
  src/components/accordion/accordion.stories.js
  src/components/button/button.js
  src/components/button/button.stories.js
  src/components/list-item/list-item.js
  src/components/list-item/list-item.stories.js
  src/components/list-item/list-item.styles.scss
  src/icons/arrow-down.svg
  src/styles.scss
Labels: bug, component, high priority
